### ISSUE TITLE
Failed to read the 'localStorage' property from 'Window': Access is denied for this document

### ISSUE THREAD

**Issue by yongyi520** [nprutan/shopify-cookieless-auth-demo#1]
I am using your example repository and here's the issue I have encountered

**Problem**
When I set the browser to block 3rd party cookie, I get Error was not caught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

![Screen Shot 2020-12-17 at 3 38 32 PM](https://user-images.githubusercontent.com/10789851/102465482-486c9800-4080-11eb-9f3c-1b0d8c5b3cc8.png)

![Screen Shot 2020-12-17 at 3 55 04 PM](https://user-images.githubusercontent.com/10789851/102465572-64703980-4080-11eb-9b27-4b3721377c68.png)

**Potential Issue**
Seems like this is related to iFrame issues:
https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document

**Questions**
1. Have you encountered this issue before when testing on shopify?

**Comment by yongyi520** [comment]
ok this only happens in dev environment when the third party cookie is blocked in chrome

only next.js dev is calling "pre-render indicator"

It does not happen in production.

**Comment by nprutan** [comment]
@yongyi520 Thanks for raising this issue. I'll check into this the next time I bump package versions.
