### ISSUE TITLE
oauth error - same_site_cookies

### ISSUE THREAD

**Issue by rozenmd** [nprutan/shopify-cookieless-auth-demo#3]
Hey, this project looks awesome - but I'm having issues trying to get it running.

I've tried:
1. Running `shopify create`, running through the wizard
2. Then cloning this repo and copying over the existing files

I then run `yarn dev`, update the app's URL to the ngrok address, visit the ngrok url (`https://NGROK_ID.ngrok.io/?shop=SHOP_URL.myshopify.com`), approve the app, get redirected to Shopify, to this error:

![image](https://user-images.githubusercontent.com/3822106/104729291-518a7b00-578c-11eb-8afb-c2c1bf9c7bdb.png)

I've also tried just cloning this repo, and copying over my `.env` and `.shopify-cli.yml`, getting the same error.
I've also tried deploying this repo to Vercel, and getting the same error.

Any tricks to getting it to work?

**Comment by nprutan** [comment]
Hi @rozenmd, thanks for checking out the project!

Make sure you’ve upgraded to the latest Shopify CLI, then create an app through the CLI.

Now cd into the cloned demo repo and run `shopify connect`, and connect with the project that you’ve just created with the CLI when given the option. This will create the `.env` and `.shopify-cli.yml` files with the right credentials for the project.

Next, run `shopify serve` in a terminal and then go to your Shopify partner site and choose the app to install on a dev site. 

Watch your terminal for the output of the OAuth access token. 

Copy the token, go into the server.js file in the demo repo and paste into the locations where it’s noted as “persistedToken”.

Restart your `shopify serve` instance in your terminal. 

Go back to your dev store, navigate out of the app and into the apps page and click on the installed app and you should be able to see the results of a sample GraphQL query on your shop data.

Make sure to open the JS console in the browser while doing this. You’ll see some output about the wrong shopOrigin, but this is just from Next.js and SSR running first. When the page finally loads in the browser you’ll get the shopOrigin from the route and it will be used in the GraphQL call.

Let me know if you still have issues!
Nate

**Comment by rozenmd** [comment]
Just confirming, running `shopify version` gives me `1.5.0`, which seems to be the latest version on GitHub.

Running `shopify connect` in this cloned repo gives me:
```
✗ You are not in a Shopify app project
⭑ Run shopify create to create your app
```
Are there missing files from this repo? Or should I be cloning this demo repo *into* the new project I create?

**Comment by rozenmd** [comment]
Oh awesome - it was the `persistedToken` bit I was missing.

Copying it from console and hardcoding it made it work. Cheers!

**Comment by nprutan** [comment]
Great, glad to hear you got it working. Have a nice weekend!

**Comment by pratiknikam** [comment]
@nprutan I'm little confused about `persistedToken` in `server.js`. I followed steps mentioned above and terminal never showed me that token.

Even if it does, are we suppose to hardcode that in code? I'm just trying to connect dots here regarding its usage.

**Comment by pratiknikam** [comment]
@nprutan I'm little confused about `persistedToken` in `server.js`. I do see access token on terminal but I'm not sure why we should hardcode it. It should be dynamic as it's going to be different for every store.

```
{
   shopify: {
     shop: 'myshopify1234.myshopify.com',
     accessToken: 'shpat_c7ab83344547ca344401330fb2791b9'
   }
 }
```

**Comment by nprutan** [comment]
Hi Pratik, the token should not be hardcoded. I just used "persistedToken"
as a placeholder. In my own production code I am pulling this saved token
out of a GQL store in AWS.

For example:

const settings = await getAppSettings(shop);
const token = settings.data.getUser && settings.data.getUser.token;

The getAppSettings function returns the GQL query including the token.

Feel free to use whatever persistence mechanism you would like here.

Hope that helps,
Nate
